jpackage --type pkg \
  --input ./input-pv/ \
  --resource-dir ./resources-pv/ \
  --main-jar PornViewer.jar \
  --main-class com.plovdev.pornviewer.Launcher \
  --name "PornViewer" \
  --app-version "1.6.8" \
  --vendor "PlovDev" \
  --copyright "© 2026 PlovDev. Все права защищены." \
  --description "Безопасный и анонимный просмотр видео 18+ с шифрованием и поддержкой плагинов" \
  --dest dist \
  --icon ./files/icon.icns \
  --java-options "-Xmx2G" \
  --java-options "-Dfile.encoding=UTF-8" \
  --mac-package-identifier "com.plovdev.pornviewer" \
  --mac-package-name "PornViewer" \
  --mac-app-category "public.app-category.entertainment" \
  --license-file ./files/LICENSE.txt \
  --about-url "https://github.com/anton-1488/PornViewer" \
  --file-associations ./files/video-assoc.properties \
  --temp build_temp \
  --verbose